### PR TITLE
Make Username:Password work with other schools.

### PR DESCRIPTION
**Pull request by PolyAnthi**
Add a Enter School field which uses the API to get the school id and form the URL.

### CODE REVIEW

**Comment by PolyAnthi** [comment]
@Gwyd0

**Comment by littleAndyy** [comment]
u a legend my bruda, was about to open an issue report

**Comment by littleAndyy** [comment]
image
not my school but ye. not sure what I'm doing wrong.

[SPARX BWK LOGS]
[START TIME] 06-11-2022-20-11-45
--- [SETTINGS] --- 
[USER] username
[PASSWORD] password
[SCHOOL] (my school was inputted here)
[AUTOCONTINUE] (my school was inputted here in the logs somehow)
[AUTOBWC] True
[VERSION] True
--- [WORK LOGS] --- 
20:11:57  [LOG] New Log Made [NAME] 06-11-2022-20-11-45. 
20:11:57  [MAIN] If Chrome fails to open. Install the newest version of Chromedriver. 
20:12:06  [MAIN] Chrome Version: 107.0.5304.88

**Comment by littleAndyy** [comment]
inputted my own unique auth url in the code, logs in fine now

**Comment by bruhalfie** [comment]
how do you input it because i input my own URL in the code in notes and save it and it dont work

**Comment by PolyAnthi** [comment]
Posted a new commit, should fix issue.

**Pull request closed without merging**
